# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-27 23:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('C4D', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RawLandRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('office', models.CharField(max_length=3)),
                ('document_date', models.DateField(blank=True, null=True)),
                ('recording_date', models.DateField(blank=True, null=True)),
                ('document_type', models.CharField(blank=True, max_length=128, null=True)),
                ('title_company', models.CharField(blank=True, max_length=256, null=True)),
                ('legal_description', models.CharField(blank=True, max_length=256, null=True)),
                ('lot', models.CharField(blank=True, max_length=64, null=True)),
                ('block', models.CharField(blank=True, max_length=32, null=True)),
                ('unit', models.CharField(blank=True, max_length=32, null=True)),
                ('area', models.FloatField(blank=True, null=True)),
                ('phase', models.CharField(blank=True, max_length=32, null=True)),
                ('tract', models.IntegerField(blank=True, null=True)),
                ('increment', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('lot_sf', models.FloatField(blank=True, null=True)),
                ('building_sf', models.FloatField(blank=True, null=True)),
                ('map_document', models.IntegerField(blank=True, null=True)),
                ('building_type', models.CharField(blank=True, max_length=32, null=True)),
                ('year_built', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('construction_type', models.CharField(blank=True, max_length=32, null=True)),
                ('building_condition', models.CharField(blank=True, max_length=32, null=True)),
                ('island', models.CharField(blank=True, max_length=256, null=True)),
                ('municipality', models.CharField(blank=True, max_length=256, null=True)),
                ('condominium', models.CharField(blank=True, max_length=256, null=True)),
                ('instrument_number', models.CharField(blank=True, max_length=32, null=True)),
                ('fy_number', models.CharField(blank=True, max_length=64, null=True)),
                ('cnmi_file_numer', models.CharField(blank=True, max_length=32, null=True)),
                ('lcdn', models.IntegerField(blank=True, null=True)),
                ('book', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('page', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('amount', models.FloatField(blank=True, default=0.0, null=True)),
                ('recording_fees', models.FloatField(blank=True, default=0.0, null=True)),
                ('land_tax', models.FloatField(blank=True, default=0.0, null=True)),
                ('building_tax', models.FloatField(blank=True, default=0.0, null=True)),
                ('land_appraised_value', models.FloatField(blank=True, default=0.0, null=True)),
                ('building_appraised_value', models.FloatField(blank=True, default=0.0, null=True)),
                ('remarks', models.CharField(blank=True, max_length=256, null=True)),
            ],
        ),
    ]
