# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-08-17 03:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('C4D', '0002_rawlandrecord'),
    ]

    operations = [
        migrations.AlterField(
            model_name='importlog',
            name='start_ts',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
