# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-21 17:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('C4D', '0003_auto_20160531_2120'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Property',
            new_name='Plot',
        ),
        migrations.RenameField(
            model_name='landrecord',
            old_name='property',
            new_name='plot',
        ),
        migrations.AlterField(
            model_name='rawlandrecord',
            name='tract',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
