# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-21 18:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('C4D', '0004_auto_20160721_1703'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rawlandrecord',
            old_name='cnmi_file_numer',
            new_name='cnmi_file_number',
        ),
    ]
