# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-08-15 22:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('C4D', '0007_auto_20160815_2214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rawlandrecord',
            name='condominium',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='rawlandrecord',
            name='grantee',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='rawlandrecord',
            name='grantor',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='rawlandrecord',
            name='legal_description',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='rawlandrecord',
            name='municipality',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='rawlandrecord',
            name='recording_date',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='rawlandrecord',
            name='remarks',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='rawlandrecord',
            name='title_company',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
    ]
