# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-08-16 22:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('C4D', '0010_auto_20160816_1429'),
    ]

    operations = [
        migrations.AlterField(
            model_name='importlog',
            name='start_ts',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='rawlandrecord',
            name='amount',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='rawlandrecord',
            name='area',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='rawlandrecord',
            name='block',
            field=models.CharField(blank=True, db_index=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='rawlandrecord',
            name='book',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='rawlandrecord',
            name='building_appraised_value',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='rawlandrecord',
            name='building_condition',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='rawlandrecord',
            name='building_sf',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='rawlandrecord',
            name='building_tax',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='rawlandrecord',
            name='building_type',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='rawlandrecord',
            name='cnmi_file_number',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='rawlandrecord',
            name='construction_type',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='rawlandrecord',
            name='document_date',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='rawlandrecord',
            name='fy_number',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='rawlandrecord',
            name='grantee',
            field=models.CharField(blank=True, db_index=True, max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='rawlandrecord',
            name='grantor',
            field=models.CharField(blank=True, db_index=True, max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='rawlandrecord',
            name='increment',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='rawlandrecord',
            name='instrument_number',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='rawlandrecord',
            name='land_appraised_value',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='rawlandrecord',
            name='land_tax',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='rawlandrecord',
            name='lcdn',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='rawlandrecord',
            name='legal_description',
            field=models.CharField(blank=True, db_index=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='rawlandrecord',
            name='lot',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='rawlandrecord',
            name='lot_sf',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='rawlandrecord',
            name='map_document',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='rawlandrecord',
            name='page',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='rawlandrecord',
            name='phase',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='rawlandrecord',
            name='recording_date',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='rawlandrecord',
            name='recording_fees',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='rawlandrecord',
            name='tract',
            field=models.CharField(blank=True, db_index=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='rawlandrecord',
            name='unit',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='rawlandrecord',
            name='year_built',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
